### ISSUE TITLE
Why use ./adb in Linux version

### ISSUE THREAD

**Issue by Jipok** [realKarthikNair/realme-ui-debloater#10]
Connecting the phone will still require udev rules which are installed with the android-tools package. Which seems to be in every popular Linux distribution. So why distribute some obscure adb binary?

**Comment by realKarthikNair** [comment]
> Which seems to be in every popular Linux distribution

popular distros have ancient versions of adb in official repos

> Connecting the phone will still require udev rules  

1. Not in every case
2. a normal linux user will figure that out anyway, if needed

> So why distribute some obscure adb binary?

Just to make things simpler. Also, they are official binaries but got your point.
