### ISSUE TITLE
Realme Pad packages

### ISSUE THREAD

**Issue by ghost** [realKarthikNair/realme-ui-debloater#4]
Hello, I extracted the following APKs from a new Realme Pad tablet (can upload them somewhere if needed.)

Certificates are by oplus.com (Oplus, DongGuan, CN)

**com.oppo.rftoolkit** - 111,5 kb
monitors the broadcast action events (BOOT_COMPLETED)
activities:
com.oppo.rftoolkit.RfToolkitCustomerService
com.oppo.rftoolkit.RfToolkitBandSelect
com.oppo.rftoolkit.RfToolkitAgingTest
com.oppo.rftoolkit.RfToolkitAgingSubTest

**com.oppoex.afterservice** "After-Sales Service" - 11,3 mb
checks Build.FINGERPRINT and Build.MANUFACTURER
uses SQLite Database
reads/writes to External Storage
access internet, sms, gps/wifi
hardcoded URLs:
https://after-sales-eu.coloros.com/after_service_information_india.xml
https://after-sales-eu.coloros.com/after_service_information.xml
activities:
com.oppoex.afterservice.MainActivity
com.oppoex.afterservice.activity.CustomHotline
com.oppoex.afterservice.activity.BaseActivity
com.oppoex.afterservice.activity.CustomCenterIndia

**com.ape.mtbf** "MTBF Tools" - 8,7 mb
Dialer Code: 68238665
uses SQLite Database
reads/writes to External Storage
all sorts of permissions (camera, mic, battery, radio, led, sim, gps, nfc...)
hardcoded URLs (include a book!):
http://www.amazon.co.uk/exec/obidos/ASIN/0571058086/qid=1099836249/sr=1-3/ref=sr_1_11_3/202-6017285-1620664
http://www.amazon.co.uk/exec/obidos/ASIN/0571058086qid=1099836249/sr=1-3/ref=sr_1_11_3/202-6017285-1620664
http://www.andykhan.com/jexcelapi

**com.ape.factory** - 7,4 mb
checks Build.SERIAL and ro.build.type
all sorts of permissions and activities (camera, mic, battery, radio, led, sim, gps, nfc...)
reads/writes to External Storage

**com.oplus.batterywarning** - 4,3 mb
uses accessibility, gps/wifi

**com.yha.runtime** "RuntimeTest" - 31 mb
reads/writes to External Storage
uses wifi, camera, sensors, mic, etc.
lots of activities (hardware tests?):
FlashTest, VibratorTest, WIFITest, Reboot, LCDTest, AudioLoop, VideoTest, CameraTest, Tester3dTeapot, FullMemTest, ScreenSaver...

**com.yha.engineersecret** - 407 kb
reads/writes to External Storage
gets the IMEI, uses gps/wifi
lots of activities (hardware tests?):
IMeiAndPcbCheck, DeviceListActivity, CheckSoftwareInfo, GpsActivity, BluetoothTest, BluetoothSearch, LteSarTest, NetworkSearch, DecryptionActivity...

**com.sprd.logmanager** "YLog" - 3 mb
ro.product.device
High Intent Priority (1000)
uses SQLite Database
reads/writes to External Storage
hardcoded URLs:
[www.google.com](http://www.google.com/)

**com.spreadtrum.sgps** "SGPS" - 302 kb
Dialer Code: 2266
internet and gps access
reads/writes to External Storage
hardcoded URLs:
http://earth.google.com/kml/2.0

**com.android.phone.injection** - 8,6 kb
very small apk, it's a single class which assigns a constant numeric value to a variable called telephony_injection

**com.unisoc.phone** "LockAssistant" - 735 kb
runs before the user unlocks the device (direct-boot aware)
reads imei, sms, call log, uses gps/wifi
activities:
com.unisoc.phone.smartcallforward.SmartDualSIMActivity
com.unisoc.phone.simlock.ChooseSimLockTypeActivity
com.unisoc.phone.simlock.NckSimLockActivity
com.unisoc.phone.simlock.UnLockActivity
com.unisoc.phone.uplmn.UplmnSettings
com.unisoc.phone.simlock.SimLockActivity
com.unisoc.phone.SimPlugActivity

**com.sprd.uasetting** "UASetting" - 45 kb
reads/writes to External Storage

**Comment by realKarthikNair** [comment]
Most of the apps you've listed are necessary for service/after sales service purposes

Can you send me the exact model number of the device? I can't understand what spreadtrum aka unisoc system apps are doing there while the tablet is supposed to have a mediatek SoC.

**Comment by bryce-lynch** [comment]
This device is the Pad Mini (RMP2106) which uses the Unisoc T616 processor, [this one](https://www.gsmarena.com/realme_pad_mini-11446.php) has similar specs.

Yes I know those apps are for service purposes but given the amount of permissions and network access I prefer to disable them, YMMV.

**Comment by realKarthikNair** [comment]
Okay got it. I am planning a preference based menu in next month's release. I will add those packages along with much more packages in that commit.

For instance, I'll add optional menus that asks to remove certain packages optionally, ie once the general bloatwares are removed, e.g., for service purpose applications there will be a prompt that looks like `Do you want to disable/uninstall system apps used for after-sales service purposes? [Y/N]`

**Implementing it is easy yet I can not do it right now since before every commit I obtain around 4-5 diffrent realme devices and test the latest changes to ensure system stability. But i do not have access to those devices right now since my acquaints are busy with Christmas/new year week**

You can manually debloat/manually add those packages in the script for now, after ensuring that the removal of them doesn't break system. 

Please let me know incase of any queries.

Thank you for making realme ui debloater better.

**Comment by realKarthikNair** [comment]
1. I no longer use realme UI
2. I lost interest in this repo

so closing
