### ISSUE TITLE
Integrate more

### ISSUE THREAD

**Issue by NoelJacob** [realKarthikNair/realme-ui-debloater#8]
I would suggest integrating more from https://www.reddit.com/r/Realme/comments/w12bbk/realme_rui_20_rui_30_debloat_list/ and https://www.getdroidtips.com/realme-debloat-apps-list/ but needs testing as some cause bootloop.

**Comment by realKarthikNair** [comment]
Thank you. I'll surely look into those once I'm done with my exams.

**Comment by vjaykrsna** [comment]
any update on this?
and also i had a question, can we improve the experience more than just debloating the apps like disabling unnecessary logs and services and more

**Comment by realKarthikNair** [comment]
1. I no longer use realme UI
2. I lost interest in this repo

so closing
